"""Add one to many relationship

Revision ID: 07c5ac0ad2ef
Revises: 39aaae8582f2
Create Date: 2021-04-26 13:58:12.312116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c5ac0ad2ef'
down_revision = '39aaae8582f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'merchants', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchants', type_='foreignkey')
    op.drop_column('merchants', 'user_id')
    # ### end Alembic commands ###
